#! /bin/bash
version=2.0
git pull
rm -f acsl_*_all.deb
rm -f Debian/usr/bin/acsl
{
  echo '#!/bin/bash'
  echo "man $@" >>Debian/usr/bin/acsl
  for f in src/*; do
    sed '1{/^#!\/.*sh$/d}' "$f"
  done
} >Debian/usr/bin/acsl

cd Debian
md5sum usr/bin/acsl | tee DEBIAN/md5sums
cd ..
fakeroot dpkg-deb --build Debian .
sudo dpkg -i acsl_${version}_all.deb

tmp=gh repo list acsl-tcu | grep project | fmt | awk '{print $1}' | sed -e "s|acsl-tcu/project
_||g"
sed -i "s|PROJECT_LIST|$tmp|g" acsl.bash
git add .
git commit -m "update acsl command"
git push

sed -i "s/v[0-9]\+\.[0-9]\+/v${version}/g" ./README.md
sed -i "s/acsl_[0-9]\+\.[0-9]\+_all.deb/acsl_${version}_all.deb/g" ./README.md


echo https://github.com/acsl-tcu/acsl/releases/edit/v${version}
explorer.exe .
