#!/usr/bin/env bash
ACSL_VERSION="3.3"

#############################################################
# Assets
#############################################################
# Usageを表示
function usage() {
  echo $1
  cat <<_EOT_
Usage:
  $(basename $0) [-a] [-B] [-b bargv] ...

Description:
  XXX

Options:
  -a オプションa
  -B オプションB
  -b オプションbの引数値を指定
  -h ヘルプ表示

_EOT_
  exit 1
}

# オプションフラグ用変数初期化
function initOptionFlags() {
  for char in {{a..z},{A..Z}}; do
    eval OPT_FLAG_${char}=0
  done
}

# オプション解析結果を表示
function printOptions() {
  echo "### 指定オプション一覧"
  for char in {{a..z},{A..Z}}; do
    opt=$(eval echo \${OPT_FLAG_${char}:-""})
    optarg=$(eval echo \${OPT_VALUE_${char}:-""})
    if [[ $opt = 1 ]]; then
      echo "opt=-${char} ${optarg:+optarg=${optarg}}"
    fi
  done
  echo
}

function print_acsl_version() {
  echo "acsl ${ACSL_VERSION}"
}

##################################################
function git_pull() {
  .acsl/docker/common/scripts/gpull $1
}
function colcon_build() {
  .acsl/commands/scripts/build_project $@
}
function docker_push() {
  .acsl/commands/scripts/dpush image_${PROJECT}
}

function check_acsl() {
  if [[ -v ORGPATH ]]; then
    echo ACTIVE ACSL project
    echo "ACSL_WORK_DIR : $ACSL_WORK_DIR"
    echo "PROJECT : $PROJECT"
    echo "ROS Domain ID : $ROS_DOMAIN_ID"
    return 0
  else
    return 1
  fi
}

function change_dir_for_init() {
  if [ "${1-}" = "init" ]; then
    echo "Initialize project in current folder"
  elif [[ -d $1 ]]; then
    echo "Move to $1"
    cd $1
  else
    echo "Create new directory $1 for initialization"
    mkdir $1
    cd $1
  fi
}

function check_empty() {
  if [ -z "$(find . -mindepth 1 -print -quit)" ]; then
    return 0
  else
    return 1
  fi
}
